services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      database:
        condition: service_healthy
      mailer:
        condition: service_started
    environment:
      DATABASE_URL: "mysql://root:supersaiyan@database:3306/db_shy?serverVersion=8.0"
      MAILER_DSN: "smtp://mailer:1025"

  database:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_shy
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-psupersaiyan"]
      interval: 5s
      timeout: 5s
      retries: 5

  mailer:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /tmp
    volumes:
      - mailhog_data:/tmp

volumes:
  db-data:
  mailhog_data: